name: CI

on: [push]

env:
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/reditus-test?schema=public&sslmode=disable

jobs:
  run-all-checks:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.4.0
      uses: actions/setup-node@v1
      with:
        node-version: 14.4.0
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm 
        key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-
          ${{ runner.OS }}-
    - name: Install node dependencies
      run: npm install
    - name: Run ESLint
      run: npm run lint
    - name: Setup prisma client
      run: npx prisma generate
    - name: Run Typescript typechecking
      run: npm run typecheck
    - name: Setup database
      run: npx prisma migrate deploy --preview-feature
    - name: Run Tests
      run: npm test -- --detectOpenHandles --forceExit