name: CI

on: [push]

jobs:
  run-all-checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.4.0
      uses: actions/setup-node@v1
      with:
        node-version: 14.4.0
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm 
        key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-
          ${{ runner.OS }}-
    - name: Install node dependencies
      run: npm install
    - name: Run ESLint
      run: npm run lint
    - name: Run Typescript typechecking
      run: npm run typecheck
    - name: Run Tests
      run: npm test